/* Generated by userscript/build-extension-parser.mjs. Do not edit directly. */
(() => {
"use strict";
  const CURRENCIES = {
    USD: { dec: 2, zh: '美元' },
    CNY: { dec: 2, zh: '人民币' },
    JPY: { dec: 0, zh: '日元' },
    EUR: { dec: 2, zh: '欧元' },
    GBP: { dec: 2, zh: '英镑' },
    HKD: { dec: 2, zh: '港元' },
    TWD: { dec: 0, zh: '新台币' },
    KRW: { dec: 0, zh: '韩元' },
    SGD: { dec: 2, zh: '新加坡元' },
    AUD: { dec: 2, zh: '澳元' },
    CAD: { dec: 2, zh: '加元' },
    NZD: { dec: 2, zh: '新西兰元' },
    SEK: { dec: 2, zh: '瑞典克朗' },
    NOK: { dec: 2, zh: '挪威克朗' },
    DKK: { dec: 2, zh: '丹麦克朗' },
    THB: { dec: 2, zh: '泰铢' },
    MYR: { dec: 2, zh: '林吉特' },
    PHP: { dec: 2, zh: '菲律宾比索' },
    VND: { dec: 0, zh: '越南盾' },
    INR: { dec: 2, zh: '印度卢比' },
    BRL: { dec: 2, zh: '巴西雷亚尔' },
  };

  /*
   * 标记表。code 为 null 表示「有歧义」，amb 是候选（第一个是默认倾向）。
   * 顺序不重要（构造正则时按长度降序），但同一个符号不要重复。
   */
  const MARKERS = [
    { p: 'US$', code: 'USD', conf: 0.95 },
    { p: 'HK$', code: 'HKD', conf: 0.98 },
    { p: 'NT$', code: 'TWD', conf: 0.98 },
    { p: 'A$', code: 'AUD', conf: 0.9 },
    { p: 'C$', code: 'CAD', conf: 0.9 },
    { p: 'S$', code: 'SGD', conf: 0.9 },
    { p: 'NZ$', code: 'NZD', conf: 0.9 },
    { p: 'R$', code: 'BRL', conf: 0.9 },
    { p: 'RM', code: 'MYR', conf: 0.85 },
    { p: 'CN¥', code: 'CNY', conf: 0.95 },
    { p: 'JP¥', code: 'JPY', conf: 0.95 },
    { p: '美元', code: 'USD', conf: 1 },
    { p: '美金', code: 'USD', conf: 1 },
    { p: '人民币', code: 'CNY', conf: 1 },
    { p: '离岸人民币', code: 'CNY', conf: 1 },
    { p: 'RMB', code: 'CNY', conf: 1 },
    { p: 'CNY', code: 'CNY', conf: 1 },
    { p: '日元', code: 'JPY', conf: 1 },
    { p: '日圆', code: 'JPY', conf: 1 },
    { p: '日本円', code: 'JPY', conf: 1 },
    { p: 'JPY', code: 'JPY', conf: 1 },
    { p: 'USD', code: 'USD', conf: 1 },
    { p: 'EUR', code: 'EUR', conf: 1 },
    { p: 'GBP', code: 'GBP', conf: 1 },
    { p: 'HKD', code: 'HKD', conf: 1 },
    { p: 'TWD', code: 'TWD', conf: 1 },
    { p: 'KRW', code: 'KRW', conf: 1 },
    { p: 'SGD', code: 'SGD', conf: 1 },
    { p: 'AUD', code: 'AUD', conf: 1 },
    { p: 'CAD', code: 'CAD', conf: 1 },
    { p: 'THB', code: 'THB', conf: 1 },
    { p: 'MYR', code: 'MYR', conf: 1 },
    // 注意：PHP / INR / VND / BRL 故意不做裸代码识别 ——
    // "PHP 8.2" 在开发者页面上是编程语言，不是菲律宾比索；这些币种只认符号（₱ ₹ ₫ R$）
    { p: '欧元', code: 'EUR', conf: 1 },
    { p: '英镑', code: 'GBP', conf: 1 },
    { p: '港元', code: 'HKD', conf: 1 },
    { p: '港币', code: 'HKD', conf: 1 },
    { p: '新台币', code: 'TWD', conf: 1 },
    { p: '台币', code: 'TWD', conf: 1 },
    { p: '韩元', code: 'KRW', conf: 1 },
    { p: '新加坡元', code: 'SGD', conf: 1 },
    { p: '澳元', code: 'AUD', conf: 1 },
    { p: '加元', code: 'CAD', conf: 1 },
    { p: '泰铢', code: 'THB', conf: 1 },
    { p: '越南盾', code: 'VND', conf: 1 },
    { p: '₫', code: 'VND', conf: 1 },
    { p: '₱', code: 'PHP', conf: 1 },
    { p: '₹', code: 'INR', conf: 1 },
    { p: '₩', code: 'KRW', conf: 1 },
    { p: '฿', code: 'THB', conf: 1 },
    { p: '€', code: 'EUR', conf: 1 },
    { p: '£', code: 'GBP', conf: 1 },
    { p: '円', code: 'JPY', conf: 0.95 },
    { p: '원', code: 'KRW', conf: 0.9 },
    // 歧义标记：靠证据链决定
    { p: '元', code: 'CNY', conf: 0.9, amb: ['CNY', 'TWD'] },
    { p: 'kr', code: null, conf: 0.5, amb: ['SEK', 'NOK', 'DKK'] },
    { p: '¥', code: null, conf: 0.5, amb: ['CNY', 'JPY'] },
    { p: '￥', code: null, conf: 0.5, amb: ['CNY', 'JPY'] },
    { p: '$', code: 'USD', conf: 0.7, amb: ['USD', 'CAD', 'AUD', 'HKD', 'SGD', 'NZD', 'TWD'] },
  ];

  const TLD_CURRENCY = {
    jp: 'JPY', cn: 'CNY', tw: 'TWD', hk: 'HKD', kr: 'KRW', sg: 'SGD', th: 'THB', my: 'MYR',
    vn: 'VND', ph: 'PHP', in: 'INR', br: 'BRL', se: 'SEK', no: 'NOK', dk: 'DKK',
    au: 'AUD', ca: 'CAD', nz: 'NZD', uk: 'GBP',
  };

  const MAGNITUDE = { 万: 1e4, 萬: 1e4, 亿: 1e8, 億: 1e8, 千: 1e3, 百: 1e2, k: 1e3, K: 1e3, M: 1e6 };
  const SP = '[ \\u00A0\\u2009\\u202F]?';                 // 只允许同行空格
  const NUM_SRC = '\\d{1,3}(?:[,\\u00A0\\u2009\\u202F ]\\d{3})+(?:[.,]\\d+)?|\\d+(?:[.,]\\d+)*';
  const MAG_SRC = '(?:[万千百萬億亿kKM](?![A-Za-z]))?';    // 量级后面不能紧跟字母（100 km / 100 MB）
  const YUAN_PREFIX_DENY = new Set('美日欧港台韩新澳加比泰马越英法德俄瑞丹挪');

  function escRe(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

  let _reSrc = null;
  /**
   * 每次返回一个**全新的** RegExp。
   * 教训：全局正则的 lastIndex 是共享可变状态。markerCensus() 会在 parseAll() 的循环中间
   * 用同一个正则去扫另一段文本，把 lastIndex 复位，于是 parseAll 从头再来 → 死循环。
   * 所以这里只缓存正则源码，绝不缓存正则对象本身。
   */
  function amountRe() {
    if (!_reSrc) {
      const alt = MARKERS.map(function (m) { return escRe(m.p); }).sort(function (a, b) { return b.length - a.length; }).join('|');
      // 组：1=前缀标记 2=数字 3=量级 4=后缀标记
      _reSrc = '(?:(' + alt + ')' + SP + ')?(' + NUM_SRC + ')' + SP + '(' + MAG_SRC + ')(?:' + SP + '(' + alt + '))?';
    }
    return new RegExp(_reSrc, 'g');
  }

  const markerByText = new Map(MARKERS.map(function (m) { return [m.p, m]; }));

  /** "1,299.50" / "1.299,50" / "1 234" / "1.5M" → number（不含量级） */
  function parseNumber(raw) {
    let s = String(raw).replace(/[\s\u00A0\u2009\u202F]/g, '');
    if (!s) return null;
    const dot = s.lastIndexOf('.');
    const com = s.lastIndexOf(',');
    if (dot >= 0 && com >= 0) {
      s = com > dot ? s.replace(/\./g, '').replace(/,/g, '.') : s.replace(/,/g, '');
    } else if (com >= 0) {
      if (/^\d{1,3}(,\d{3})+$/.test(s)) s = s.replace(/,/g, '');
      else if (/^\d+,\d{1,2}$/.test(s)) s = s.replace(',', '.');
      else s = s.replace(/,/g, '');
    } else if (dot >= 0) {
      if (/^\d{1,3}(\.\d{3})+$/.test(s)) s = s.replace(/\./g, '');
    }
    const v = parseFloat(s);
    return Number.isFinite(v) ? v : null;
  }

  function hits(text, re) { const m = String(text).match(re); return m ? m.length : 0; }

  function tldOf(host) {
    const m = String(host || '').toLowerCase().match(/\.([a-z]{2,})$/);
    return m ? m[1] : '';
  }

  function keywordCounts(text) {
    const t = String(text || '');
    return {
      jp: hits(t, /税込|税抜|送料無料|ポイント|決済|日本円|為替|お届け|在庫あり|カート/g),
      cn: hits(t, /含税|包邮|免运费|人民币|元起|优惠券|国内|发货|清仓|折后/g),
      ko: hits(t, /배송|무료|결제|할인|원/g),
    };
  }

  /** 全文货币标记普查：数字相邻的算强证据（census['¥']），裸标记算弱证据（census['~¥']） */
  function markerCensus(text) {
    const src = String(text || '');
    const out = {};
    const counts = {};
    const re = amountRe();
    re.lastIndex = 0;
    let m;
    while ((m = re.exec(src)) !== null) {
      if (m[0] === '') { re.lastIndex++; continue; }
      const mk = m[1] || m[4];
      if (mk) out[mk] = (out[mk] || 0) + 1;
    }
    for (const marker of MARKERS) {
      const n = hits(src, new RegExp(escRe(marker.p), 'g'));
      if (n > 0) {
        const adjacent = out[marker.p] || 0;
        const bare = Math.max(0, n - adjacent);
        if (bare > 0) out['~' + marker.p] = (out['~' + marker.p] || 0) + bare;
        counts[marker.p] = n;
      }
    }
    return out;
  }

  const EMPTY_PROFILE = {
    lang: '', host: '', tld: '',
    ratios: { kana: 0, hangul: 0, han: 0, latin: 0 },
    counts: { kana: 0, hangul: 0, han: 0, latin: 0 },
    census: {}, keywords: {}, textLen: 0,
  };

  /** 把旧的 / 简化的 ctx 补全成 profile；ctx.profile 优先 */
  function profileOf(ctx) {
    const c = ctx || {};
    if (c.profile) return c.profile;
    const host = String(c.host || '');
    const sig = String(c.signals || '');
    return {
      lang: c.lang || '',
      host: host,
      tld: c.tld || tldOf(host),
      ratios: c.ratios || EMPTY_PROFILE.ratios,
      counts: c.counts || EMPTY_PROFILE.counts,
      census: sig ? markerCensus(sig) : {},
      keywords: sig ? keywordCounts(sig) : {},
      textLen: sig.length,
    };
  }

  /** 从 DOM 采样生成页面画像（只读，不修改页面） */
  function buildProfile(doc, win, sample) {
    const text = sample == null ? '' : String(sample);
    const count = function (re) { return hits(text, re); };
    const kana = count(/[\u3040-\u309F\u30A0-\u30FF]/g);
    const hangul = count(/[\uAC00-\uD7AF\u1100-\u11FF]/g);
    const han = count(/[\u4E00-\u9FFF\u3400-\u4DBF]/g);
    const latin = count(/[A-Za-z]/g);
    const total = Math.max(1, kana + hangul + han + latin);
    let lang = '';
    try {
      lang = doc.documentElement.getAttribute('lang') || '';
      if (!lang) {
        const meta = doc.querySelector('meta[http-equiv="content-language" i], meta[name="content-language" i], meta[property="og:locale"]');
        if (meta) lang = (meta.content || '').replace('_', '-');
      }
      if (!lang && win && win.navigator) lang = win.navigator.language || '';
    } catch (e) { /* 忽略 */ }
    let host = '';
    try { host = (win && win.location && win.location.hostname) || ''; } catch (e) { /* 忽略 */ }
    return {
      lang: lang,
      host: host,
      tld: tldOf(host),
      ratios: { kana: kana / total, hangul: hangul / total, han: han / total, latin: latin / total },
      counts: { kana: kana, hangul: hangul, han: han, latin: latin },
      census: markerCensus(text),
      keywords: keywordCounts(text),
      textLen: text.length,
    };
  }

  function candidatesOf(marker) {
    if (marker.amb && marker.amb.length > 1) return marker.amb.slice();
    if (marker.code) return [marker.code];
    return marker.amb ? marker.amb.slice() : [];
  }

  /**
   * 证据式币种识别。返回 { code, conf, alts, why, evidence, totals }
   * 每一项证据是一个独立信号，详细模式会把它们显示出来，方便你判断"为什么它认为是 JPY"。
   */
  function resolveCurrency(marker, ctx) {
    const p = profileOf(ctx);
    const cands = candidatesOf(marker);
    const ev = {};
    const add = function (code, w, why) {
      if (!w || cands.indexOf(code) < 0) return;   // 只累积候选币种的证据
      (ev[code] = ev[code] || []).push({ w: w, why: why });
    };

    const lang = String(p.lang || '').toLowerCase();
    const tld = String(p.tld || tldOf(p.host));
    const r = p.ratios || EMPTY_PROFILE.ratios;
    const counts = p.counts || EMPTY_PROFILE.counts;
    const census = p.census || {};
    const kw = p.keywords || {};
    const num = function (k) { return census[k] || 0; };
    const bare = function (k) { return census['~' + k] || 0; };
    const pct = function (x) { return (x * 100).toFixed(2) + '%'; };

    /* ① 文字体系比重：假名/谚文出现几乎只有一种解释，这是最强的一类证据 */
    if (r.kana >= 0.01) add('JPY', 6, '假名占比 ' + pct(r.kana));
    else if (r.kana >= 0.003) add('JPY', 4, '假名占比 ' + pct(r.kana));
    else if (counts.kana > 0) add('JPY', 2, '出现假名 ' + counts.kana + ' 个');
    if (r.hangul >= 0.005) add('KRW', 6, '谚文占比 ' + pct(r.hangul));
    if (r.han >= 0.05 && counts.kana === 0 && counts.hangul === 0) add('CNY', 1, '汉字页面且无假名/谚文');

    /* ② 语言标注 */
    if (/^ja/.test(lang)) add('JPY', 4, 'lang=' + lang);
    if (/^zh-(tw|hk|mo|hant)/.test(lang)) { add('TWD', 4, 'lang=' + lang); add('CNY', 1, 'lang=' + lang); }
    else if (/^zh/.test(lang)) add('CNY', 4, 'lang=' + lang);
    if (/^ko/.test(lang)) add('KRW', 4, 'lang=' + lang);
    if (/^th/.test(lang)) add('THB', 4, 'lang=' + lang);
    if (/^vi/.test(lang)) add('VND', 4, 'lang=' + lang);

    /* ③ 域名 */
    if (TLD_CURRENCY[tld]) add(TLD_CURRENCY[tld], 5, '域名 .' + tld);

    /* ④ 全文货币标记普查（"实际文本比重"） */
    const jpC = num('円') + bare('円') * 0.4 + num('JPY') + num('JP¥') + num('日元') + num('日圆') + num('日本円');
    const cnC = num('元') + bare('元') * 0.4 + num('CNY') + num('CN¥') + num('人民币') + num('RMB');
    const twC = num('NT$') + num('TWD') + num('台币') + num('新台币');
    const usC = num('$') + bare('$') * 0.5 + num('USD') + num('US$') + num('美元') + num('美金');
    if (jpC) add('JPY', Math.min(6, 1.5 * Math.min(jpC, 4)), '全文 円/JPY 系 ' + jpC.toFixed(1) + ' 次');
    if (cnC) add('CNY', Math.min(6, 1.5 * Math.min(cnC, 4)), '全文 元/CNY 系 ' + cnC.toFixed(1) + ' 次');
    if (twC) add('TWD', Math.min(6, 1.5 * Math.min(twC, 4)), '全文 NT$/TWD 系 ' + twC.toFixed(1) + ' 次');
    if (usC) add('USD', Math.min(3, 0.8 * Math.min(usC, 4)), '全文 $/USD 系 ' + usC.toFixed(1) + ' 次');

    /* ⑤ 邻近上下文（前后 60 字） */
    const local = String((ctx && ctx.local) || '');
    if (local) {
      const jpL = hits(local, /税込|税抜|送料無料|ポイント|決済|日本円|お届け/g);
      const cnL = hits(local, /含税|包邮|免运费|人民币|元起|优惠券|发货/g);
      const koL = hits(local, /배송|무료|결제|원/g);
      if (jpL) add('JPY', Math.min(5, 2 * jpL), '邻近日文词 ' + jpL + ' 个');
      if (cnL) add('CNY', Math.min(5, 2 * cnL), '邻近中文词 ' + cnL + ' 个');
      if (koL) add('KRW', Math.min(5, 2 * koL), '邻近韩文词 ' + koL + ' 个');
    }

    /* ⑥ 页面关键词 */
    if (kw.jp) add('JPY', Math.min(4, 1.2 * kw.jp), '页面日文词 ' + kw.jp + ' 处');
    if (kw.cn) add('CNY', Math.min(4, 1.2 * kw.cn), '页面中文词 ' + kw.cn + ' 处');
    if (kw.ko) add('KRW', Math.min(4, 1.2 * kw.ko), '页面韩文词 ' + kw.ko + ' 处');

    /* ⑦ 站点记忆：用户手动校准过 → 决定性，直接短路 */
    const key = String(p.host || '') + '|' + marker.p;
    const mem = (ctx && ctx.memory && ctx.memory[key]) || null;
    if (mem && CURRENCIES[mem]) {
      const forced = mem;
      return {
        code: forced, conf: 1, alts: cands, why: '站点记忆（你校准过）',
        evidence: [{ code: forced, w: 99, why: '站点记忆' }], totals: {},
      };
    }

    /* 计分：证据 + 先验（标记自身倾向） */
    const totals = {};
    cands.forEach(function (c) {
      let s = (ev[c] || []).reduce(function (a, e) { return a + e.w; }, 0);
      if (marker.code === c) s += 2;                                  // 标记本身的倾向
      if (!marker.code && cands[0] === c) s += 0.6;                    // 无倾向时给默认候选一点先手
      totals[c] = s;
    });
    const ranked = cands.slice().sort(function (a, b) { return totals[b] - totals[a]; });
    const best = ranked[0];
    const second = ranked[1];
    const margin = totals[best] - (second ? totals[second] : 0);
    let conf;
    if (totals[best] <= 0) conf = marker.code ? marker.conf * 0.7 : 0.4;
    else conf = Math.max(0.4, Math.min(0.98, 0.45 + margin / 12));
    if (marker.code === best && (ev[best] || []).length === 0) conf = Math.min(conf, marker.conf);

    const topEv = (ev[best] || []).slice().sort(function (a, b) { return b.w - a.w; });
    const why = topEv.length
      ? topEv.slice(0, 2).map(function (e) { return e.why; }).join(' + ')
      : (marker.code ? '仅凭标记 ' + marker.p : '无证据，默认 ' + best);

    return {
      code: best,
      conf: Math.round(conf * 100) / 100,
      alts: cands,
      why: why,
      evidence: (ev[best] || []).concat(ev[second] || []).sort(function (a, b) { return b.w - a.w; }),
      totals: totals,
      runnerUp: second || null,
    };
  }

  /**
   * 解析一段文本里的所有金额。
   * @param {string} text
   * @param {object} ctx  {lang, host, memory, signals?, profile?, local?}
   * @returns {{accepted: Array, rejected: Array}}
   */
  function parseAll(text, ctx, opts) {
    const includeRejected = !!(opts && opts.includeRejected);
    const accepted = [];
    const rejected = [];
    const src = String(text == null ? '' : text);
    if (!src || !/\d/.test(src)) return { accepted: accepted, rejected: rejected };
    const re = amountRe();
    re.lastIndex = 0;
    let m;
    while ((m = re.exec(src)) !== null) {
      if (m[0] === '') { re.lastIndex++; continue; }
      const push = function (reason) { if (includeRejected) rejected.push({ raw: m[0], reason: reason, at: m.index }); };

      const prefixMarker = m[1];
      const suffixMarker = m[4];
      const markerText = prefixMarker || suffixMarker;
      if (!markerText) { push('无货币标记'); continue; }
      const marker = markerByText.get(markerText);
      if (!marker) { push('未知标记'); continue; }

      const magnitude = m[3] || '';
      const rawNum = parseNumber(m[2]);
      if (rawNum == null) { push('数字无法解析'); continue; }
      const amount = rawNum * (magnitude ? (MAGNITUDE[magnitude] || 1) : 1);
      if (!(amount > 0) || amount > 1e12) { push('数值超出合理区间'); continue; }

      const start = m.index;
      const end = m.index + m[0].length;
      const before = src[start - 1] || '';
      const after = src[end] || '';

      // Do not turn a negative amount (or accounting parentheses) into a positive quote.
      if (/[-−－﹣]\s*$/.test(src.slice(0, start)) || /^\s*[-−－﹣]/.test(src.slice(end)) ||
          (/\(\s*$/.test(src.slice(0, start)) && /^\s*\)/.test(src.slice(end)))) {
        push('负数金额不支持'); continue;
      }

      if (markerText === '元' && YUAN_PREFIX_DENY.has(before)) { push('「' + before + '元」不是人民币'); continue; }
      if (markerText === 'kr' && /[A-Za-z]/.test(before)) { push('kr 前面是字母'); continue; }
      if (markerText === 'RM' && /[A-Za-z]/.test(before)) { push('RM 前面是字母'); continue; }
      if (markerText === '$' && (before === '$' || after === '{' || /[A-Za-z]/.test(before))) { push('$ 上下文可疑'); continue; }
      if ((markerText === '¥' || markerText === '￥') && /[A-Za-z]/.test(before)) { push('¥ 紧跟在字母后'); continue; }
      if (after === '%' || after === '％') { push('后面是百分号'); continue; }
      if (/^[x×*]\d/.test(src.slice(end).replace(/^[ \u00A0]/, ''))) { push('看起来是尺寸 NxN'); continue; }
      // 空格千分位后面紧跟字母 → 更可能是 "$100 500MB" 这类，整条放弃（宁可不显示，也不能显示 100500）
      if (/[ \u00A0\u2009\u202F]/.test(m[2]) && /^[A-Za-z]/.test(src.slice(end))) {
        push('空格千分位后紧跟字母（疑似单位）');
        continue;
      }

      const localCtx = Object.assign({}, ctx || {}, {
        local: src.slice(Math.max(0, start - 60), Math.min(src.length, end + 60)),
      });
      const resolved = resolveCurrency(marker, localCtx);
      accepted.push({
        raw: src.slice(start, end),
        start: start,
        end: end,
        amount: amount,
        number: rawNum,
        marker: markerText,
        prefix: !!prefixMarker,
        magnitude: magnitude,
        code: resolved.code,
        conf: resolved.conf,
        alts: resolved.alts || [],
        why: resolved.why,
        evidence: resolved.evidence || [],
        totals: resolved.totals || {},
      });
      // 兜底：保证 lastIndex 单调前进，任何被复位的正则都不会造成死循环
      if (re.lastIndex <= m.index) re.lastIndex = m.index + Math.max(1, m[0].length);
    }
    return { accepted: accepted, rejected: rejected };
  }

  function parseText(text, ctx) {
    const r = parseAll(text, ctx);
    return r.accepted.length ? r.accepted[0] : null;
  }

  function convertAmount(table, amount, from, to) {
    if (!table || !Number.isFinite(amount) || amount < 0 || amount > 1e12 ||
        !Number.isFinite(table[from]) || table[from] <= 0 || !Number.isFinite(table[to]) || table[to] <= 0) return null;
    const v = (amount / table[from]) * table[to];
    return Number.isFinite(v) ? v : null;
  }

  function formatMoney(value, code) {
    const dec = CURRENCIES[code] ? CURRENCIES[code].dec : 2;
    const a = Math.abs(value);
    let digits = dec;
    if (a > 0 && a < 1) digits = Math.min(dec + 2, 6);
    else if (a >= 1e6) digits = 0;
    return value.toLocaleString('zh-CN', { minimumFractionDigits: digits, maximumFractionDigits: digits });
  }


globalThis.FXAmountParser = {parseAll, parseText, parseNumber, convertAmount, formatMoney, resolveCurrency, markerCensus, profileOf, buildProfile, MARKERS, CURRENCIES};
})();
