#!/usr/bin/env node
/*
 * Generates extension/messages.js from extension/_locales/<locale>/messages.json.
 *
 * `_locales` is the single source of truth: Chrome reads it for the store
 * listing, and the generated table gives the in-extension language switcher the
 * same strings. A switcher is why the UI cannot simply call chrome.i18n, which
 * always follows the browser's own locale and offers no override.
 *
 *   node tools/build-i18n.mjs          write extension/messages.js
 *   node tools/build-i18n.mjs --check  fail if the committed file is stale
 */
import {readFileSync, writeFileSync} from "node:fs";
import {dirname, join} from "node:path";
import {fileURLToPath} from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const LOCALES = {zh: "zh_CN", en: "en", ja: "ja"};
const OUTPUT = join(root, "extension", "messages.js");

const read = (locale) =>
  JSON.parse(readFileSync(join(root, "extension", "_locales", locale, "messages.json"), "utf8"));

const tables = Object.fromEntries(
  Object.entries(LOCALES).map(([language, locale]) => [
    language,
    Object.fromEntries(Object.entries(read(locale)).map(([key, entry]) => [key, entry.message])),
  ]),
);

const reference = Object.keys(tables.zh);
for (const [language, table] of Object.entries(tables)) {
  const missing = reference.filter((key) => !(key in table));
  const extra = Object.keys(table).filter((key) => !reference.includes(key));
  if (missing.length || extra.length) {
    console.error(`${language}: missing ${missing.join(", ") || "-"}; extra ${extra.join(", ") || "-"}`);
    process.exit(1);
  }
}

const banner = "/* Generated by tools/build-i18n.mjs from extension/_locales. Do not edit directly. */\n";
const body = `globalThis.FXMessages = ${JSON.stringify(tables, null, 2)};\n`;
const generated = banner + body;

if (process.argv.includes("--check")) {
  const current = readFileSync(OUTPUT, "utf8");
  if (current !== generated) {
    console.error("extension/messages.js is stale; run: npm run build:i18n");
    process.exit(1);
  }
  console.log(`messages.js is up to date (${reference.length} keys)`);
} else {
  writeFileSync(OUTPUT, generated);
  console.log(`wrote extension/messages.js (${reference.length} keys x ${Object.keys(tables).length} languages)`);
}
